### ISSUE TITLE
Error compilation for windows

### ISSUE THREAD

**Issue by kikote300** [cooler-SAI/MoPCore#2]
hi i have error in Compile
error C1027: Inconsistent values for /Ym between creation and use of precompiled header

**Comment by cooler-SAI** [comment]
Really don't know how fix it, all goon in Win 7 x64, but I know about this issue.
waiting for someone who can fix it

**Comment by kikote300** [comment]
My skype : kikote300

**Comment by kikote300** [comment]
you that libraries have installed

**Comment by kikote300** [comment]
I Visual Studio 2012 64bit
OpenSSL 1.0.2c
Cmake 3.3.0
MinGW
Boots 1.57

**Comment by Orfeous** [comment]
@kikote300 in cmake uncheck "USE_COREPCH"

This will remove the precompiled headers error :)

![image](https://cloud.githubusercontent.com/assets/4233319/9430841/c511a0be-4a02-11e5-9679-d7d11278150a.png)

**Comment by kikote300** [comment]
https://gyazo.com/6f3afe11abde05305490a61a7e684d81

https://gyazo.com/2aea6d18114584fbb2131395dfde08ef

https://gyazo.com/97b6905a4733d0ae4e5c7fc9969c2902

if I take 2 PCH does not compile,
If I remove USE_COREPCH it is worse

**Comment by kikote300** [comment]
I repair error 

# Specify the maximum PreCompiled Header memory allocation limit
# Fixes a compiler-problem when using PCH - the /Ym flag is adjusted by the compiler in MSVC2012, hence we need to set an upper limit with /Zm to avoid discrepancies)
# (And yes, this is a verified , unresolved bug with MSVC... *sigh*)
string(REGEX REPLACE "/Zm[0-9]+ *" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zm2000" CACHE STRING "" FORCE)

for 

# Specify the maximum PreCompiled Header memory allocation limit
# Fixes a compiler-problem when using PCH - the /Ym flag is adjusted by the compiler in MSVC2012, hence we need to set an upper limit with /Zm to avoid discrepancies)
# (And yes, this is a verified , unresolved bug with MSVC... *sigh*)
string(REGEX REPLACE "/Zm[0-9]+ *" "" CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zm500" CACHE STRING "" FORCE)

**Comment by cooler-SAI** [comment]
Thanks a LOT, fixed :)
