### ISSUE TITLE
wow exe not connecting

### ISSUE THREAD

**Issue by Dokman** [cooler-SAI/MoPCore#6]
The same as the title

**Comment by kikote300** [comment]
la version es 5.4.7 18019 , hay que subirle la version 5.4.8

18019 version is 5.4.7 , you have to turn up the version 5.4.8

**Comment by cooler-SAI** [comment]
yeah, I know about this, need a fix

**Comment by Dokman** [comment]
with another wow exe work but it keep in conected in the character creation

**Comment by kikote300** [comment]
now do not know where to start
