### ISSUE TITLE
Character creation error

### ISSUE THREAD

**Issue by Orfeous** [cooler-SAI/MoPCore#8]
Now @kikote300 fixed the login. But there are another problems, i try to create a human monk.
When i click create it create a human warrior. When i tried it with goblin rogues it created a gnome warrior.

and also when i try to login with that char the client crash with error 132.

**Comment by kikote300** [comment]
missing opcodes

**Comment by cooler-SAI** [comment]
the same, continuing trying fix it  https://github.com/cooler-SAI/MoPCore/issues/3
